export const PHONE_BOOK_CONTACTS_CHANGED = 'PHONE_BOOK_CONTACTS_CHANGED';

export const PHONE_BOOK_CONTACTS_REQUEST = 'PHONE_BOOK_CONTACTS_REQUEST';
export const PHONE_BOOK_CONTACTS_SUCCESS = 'PHONE_BOOK_CONTACTS_SUCCESS';
export const PHONE_BOOK_CONTACTS_FAILURE = 'PHONE_BOOK_CONTACTS_FAILURE';

export const PHONE_BOOK_COUNTRIES_PHONE_CODES_CHANGED =
  'PHONE_BOOK_COUNTRIES_PHONE_CODES_CHANGED';

export const PHONE_BOOK_COUNTRIES_PHONE_CODES_REQUEST =
  'PHONE_BOOK_COUNTRIES_PHONE_CODES_REQUEST';
export const PHONE_BOOK_COUNTRIES_PHONE_CODES_SUCCESS =
  'PHONE_BOOK_COUNTRIES_PHONE_CODES_SUCCESS';
export const PHONE_BOOK_COUNTRIES_PHONE_CODES_FAILURE =
  'PHONE_BOOK_COUNTRIES_PHONE_CODES_FAILURE';
