name: Test


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install --immutable --immutable-cache
    
    - name: Test
      run: cd packages/platform-sdk && yarn run test --coverage
#     - run: yarn
#     - run: yarn build
#     - run: yarn test --coverage
